### ISSUE TITLE
Data Doesn't load on my ?

### ISSUE THREAD

**Issue by Vignesh-96** [kalagato-inc/Product-dashboard#1]
None of the charts display any data despite waiting for 30+ minutes, attaching screen shots for reference. 

System details:
System OS: Ubuntu 20.04.1 LTS
Browser: Google Chrome Version 85.0.4183.83 (Official Build) (64-bit)
![Screenshot from 2021-02-07 11-38-43](https://user-images.githubusercontent.com/78675656/107138269-8035e480-6939-11eb-8037-0ca45bfab039.png)
![Screenshot from 2021-02-07 11-40-22](https://user-images.githubusercontent.com/78675656/107138270-81671180-6939-11eb-8aff-5808c0ab5b87.png)

**Comment by Dhroov7** [comment]
Resolved
